[versions]
agp = "8.13.1"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.12.1"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-lifecycle = "2.9.6"
coilCompose = "2.7.0"
composeMultiplatform = "1.9.3"
junit = "4.13.2"
kotlin = "2.2.21"
litert_v1 = "1.4.1"
litert_v2 = "2.0.3"

[libraries]
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

litert = { module = "com.google.ai.edge.litert:litert", version.ref = "litert_v2" }
litert-gpu = { module = "com.google.ai.edge.litert:litert-gpu", version.ref = "litert_v1" }
litert-metadata = { module = "com.google.ai.edge.litert:litert-metadata", version.ref = "litert_v1" }
litert-support = { module = "com.google.ai.edge.litert:litert-support", version.ref = "litert_v1" }
tensorflow-lite-support = { group = "org.tensorflow", name = "tensorflow-lite-support" }
tensorflow-lite-metadata = { group = "org.tensorflow", name = "tensorflow-lite-metadata" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }